name: Adhoc Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to set with the docker label'
        required: true

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    runs-on: [self-hosted, ndustrial-runner-small]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
      - uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.NIO_QUAY_USERNAME }}
          password: ${{ secrets.NIO_QUAY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: quay.io/ndustrialio/postgresml:${{ github.event.inputs.tag || 'staging' }},quay.io/ndustrialio/postgresml:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          context: ./pgml-extension/
          platforms: linux/amd64, linux/arm64